jas_gene_detail
x-atlas-consortia/hs-ontology-api pull request #40
Opened 2023-10-11 18:26 UTC by AlanSimmons

2023-10-23 14:55 UTC, yuanzhou requested changes

2023-10-23 22:57 UTC, AlanSimmons commented on src/cells_index/build_index.py
> +client_url = 'https://cells.dev.hubmapconsortium.org/api/'
Changed. The build_index script is a prototype utility that is not part of the Flask application, but shares the app.cfg file.

2023-10-23 22:57 UTC, AlanSimmons commented on src/hs_ontology_api/routes/cellsclient.py
> +        self.client_url = 'https://cells.dev.hubmapconsortium.org/api/'
Done

2023-10-23 23:40 UTC, AlanSimmons commented on hs-ontology-api-spec.yaml
> +  /gene_list:
I'll meet you in the middle:

- GET `/genes` - Retrieves a high-level list of genes with parameters for pagination:
   - pages
   - genesperpage
- GET `/gene/<id> - Retrieves detailed information on a specific gene

Calling `/gene` without a parameter returns the error message `The /gene endpoint should specify a single HGNC gene identifier--e.g., /gene/MMRN1.`

2023-10-23 23:40 UTC, AlanSimmons commented on hs-ontology-api-spec.yaml
> +  /gene_detail:
I'll meet you in the middle:

- GET `/genes` - Retrieves a high-level list of genes with parameters for pagination:
   - pages
   - genesperpage
- GET `/gene/<id> - Retrieves detailed information on a specific gene

Calling `/gene` without a parameter returns the error message `The /gene endpoint should specify a single HGNC gene identifier--e.g., /gene/MMRN1.`

2023-10-24 14:28 UTC, yuanzhou approved these changes

2023-10-24 14:28 UTC, merged